- name: nginx | create build directory
  file:
    path: "{{ nginx_docker_file_destination_directory }}/nginx"
    state: directory
    mode: '0755'

- name: nginx | template config
  template:
    src: "{{ item }}.j2"
    dest: "{{ nginx_docker_file_destination_directory }}/nginx/{{ item }}"
    mode: '0644'
  loop: "{{ nginx_template_files_list }}"

- name: nginx | copy DockerFile and dependencies
  copy:
    src: "{{ role_path }}/files"
    dest: "{{ nginx_docker_file_destination_directory }}/nginx"
    mode: '0755'

- name: nginx | build container image
  community.general.docker_image:    
    build:
      path: "{{ nginx_docker_file_destination_directory }}/nginx/files"      
    name: nginx  
    source: build
    state: present

- name: nginx | run a container
  community.general.docker_container:
    name: testnginx
    image: nginx
    state: started
    restart_policy: unless-stopped
    links: "{{ links_list }}"
    ports: 
      - "80:80"
      - "443:443"
    network_mode: bridge
    volumes:
      - "{{ nginx_docker_file_destination_directory }}/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "{{ nginx_docker_file_destination_directory }}/app:/app"