version: '3'
services:

  testnginx:
    build: 
      context: ./infrafiles/nginx
      dockerfile: nginx.Dockerfile
    image: nginx
    ports: 
      - "80:80"
      - "443:443"    
    volumes:
        - ./app:/app
        - ./infrafiles/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    links:
        - testfpm

  testfpm:
    build: 
      context: ./infrafiles/php-fpm
      dockerfile: php-fpm.Dockerfile
    image: php-fpm
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
      - DATABASE_URL=${DATABASE_URL}
    volumes:
        - ./app:/app

  db:
    container_name: db
    image: postgres:12
    restart: always
    environment:
        POSTGRES_PASSWORD: password
        POSTGRES_DB: dbtest
    ports:
        - 15432:5432